name: $(Date:yyyyMMdd)$(Rev:.r)-$(SourceBranchName)

trigger:
  batch: true
  branches:
    include:
    - master
    - main
    - develop
    - patch/*
    - maint/*
    - release/*
    - feature/*
    - develop-*
    - release-*
    - feature-*

variables:
  PNPM_CACHE_FOLDER: $(Pipeline.Workspace)/.pnpm-store

jobs:
  - job: Build
    timeoutInMinutes: 0
    pool:
      name: 'Default scale set'
    steps:
      - checkout: self
        submodules: true
        clean: true

      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '14.x'

      - task: npmAuthenticate@0
        displayName: 'Set credentials in .npmrc'
        inputs:
          workingFile: '.npmrc'

      - powershell: |
          npm i -g pnpm@6.32.11
          pnpm add only-allow --global
          New-Item -Path "$(PNPM_CACHE_FOLDER)" -ItemType Directory -Force
          pnpm config set store-dir $(PNPM_CACHE_FOLDER)
        displayName: Configure PNPM

      - task: CmdLine@2
        displayName: 'PNPM install'
        inputs:
          script: 'pnpm install --shamefully-hoist --frozen-lockfile'
          workingDirectory: '$(Build.SourcesDirectory)'

      - script: pnpm run build
        displayName: 'Build'

      - script: pnpm run lint
        displayName: 'Run lint'

      - script: pnpm run test -- --code-coverage --watch=false --reporters=junit,sabarivka --browsers=ChromeHeadless
        displayName: 'Run tests with code coverage'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage results'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results/junit.xml'
