CREATE TABLE [dbo].[Location]
(
	[LocationId]				[INT]				NOT NULL	CONSTRAINT [PK_Location] PRIMARY KEY NONCLUSTERED  IDENTITY(1, 1),
	[Address]					[NVARCHAR](200)		NOT NULL,
	[TimeZoneId]				[NVARCHAR](200)		NULL,
	[Location]					[GEOGRAPHY]			NULL,
	[LastChangeReasonId]		[INT]				NULL,
	[RowVersion]				[ROWVERSION]		NOT NULL,
	[GUID]						[UNIQUEIDENTIFIER]	NOT NULL	CONSTRAINT [UK_Location(GUID)] UNIQUE NONCLUSTERED CONSTRAINT [DF_Location(GUID)] DEFAULT NEWSEQUENTIALID() ROWGUIDCOL,
)
GO
