CREATE TABLE [dbo].[User]
(
	[UserId]					[INT]				NOT NULL	CONSTRAINT [PK_User] PRIMARY KEY NONCLUSTERED  IDENTITY(1, 1),
	[UserName]					[NVARCHAR](200)		NOT NULL	CONSTRAINT [UK_User(UserName)] UNIQUE NONCLUSTERED,
	[EmailAddress]				[NVARCHAR](200)		NULL		CONSTRAINT [UK_User(EmailAddress)] UNIQUE NONCLUSTERED,
 	[Password]					[NVARCHAR](200)		NOT NULL,
	[LastChangeReasonId]		[INT]				NULL,
	[RowVersion]				[ROWVERSION]		NOT NULL,
	[GUID]						[UNIQUEIDENTIFIER]	NOT NULL	CONSTRAINT [UK_User(GUID)] UNIQUE NONCLUSTERED CONSTRAINT [DF_User(GUID)] DEFAULT NEWSEQUENTIALID() ROWGUIDCOL,
)
GO
