name: 0.0.1$(Rev:.r)_$(SourceBranchName)

trigger:
  batch: true
  branches:
    include:
    - master
    - main
    - develop
    - patch/*
    - maint/*
    - release/*
    - feature/*
    - develop-*
    - release-*
    - feature-*

variables:
  solution: '$(Build.SourcesDirectory)/PlatformFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Build
    timeoutInMinutes: 0
    pool:
      name: 'AMCS VS2022'
    steps:
      - checkout: self
        submodules: true
        clean: true

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        displayName: 'Restore NuGet packages'
        inputs:
          feedsToUse: 'config'
          nugetConfigPath: '$(Build.SourcesDirectory)/.nuget/Nuget.config'
          restoreSolution: '$(solution)'

      - task: Assembly-Info-NetFramework@2
        displayName: 'Write attributes to AssemblyInfo'
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: |
            **\AssemblyInfo.cs
          InsertAttributes: false
          FileEncoding: 'auto'
          WriteBOM: false
          Company: 'AMCS'
          Copyright: 'Copyright © AMCS $(date:YYYY)'
          VersionNumber: '$(Build.BuildNumber)'
          FileVersionNumber: '$(Build.BuildNumber)'
          InformationalVersion: '$(Build.BuildNumber)'
          AssemblyConfiguration: '$(BuildConfiguration)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsVersion: 'latest'

      - task: VSTest@2
        displayName: 'Run tests'
        inputs:
          testSelector: 'testAssemblies'
          searchFolder: '$(Build.SourcesDirectory)'
          testAssemblyVer2: |
            **\*.Tests.dll
            **\*.Test.dll
            !**\*TestAdapter.dll
            !**\obj\**
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsTestVersion: 'latest'