# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
    - master
    - develop
    - main
    - develop-*
    - release-*
  paths:
    include: 
      - Tools/AMCS.Data.SourceGenerator

pool: AMCS VS2022

variables: 
  ${{ if not(eq(variables['Build.SourceBranchName'], 'master' )) }}: 
    branchStamp: ${{ format('-{0}', variables['Build.SourceBranchName']) }}
  ${{ if eq(variables['Build.SourceBranchName'], 'master' ) }}: 
    branchStamp: ''

name: 1.0$(Rev:.r)$(branchStamp)

steps:
  - checkout: self
    submodules: recursive
    clean: true

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      feedsToUse: 'config'
      restoreSolution: '$(Build.SourcesDirectory)/Tools/AMCS.Data.SourceGenerator/AMCS.Data.SourceGenerator.sln'

  - task: VSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)/Tools/AMCS.Data.SourceGenerator/AMCS.Data.SourceGenerator.sln'
      platform: 'Any CPU'
      configuration: 'Release'
      vsVersion: 'latest'

  - task: DotNetCoreCLI@2
    inputs: 
      command: 'pack'
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      packagesToPack: '$(Build.SourcesDirectory)/Tools/AMCS.Data.SourceGenerator/AMCS.Data.SourceGenerator/AMCS.Data.SourceGenerator.csproj'
      versioningScheme: 'byBuildNumber'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.ArtifactStagingDirectory)
      contents: |
        *.nupkg
        !*.symbols.nupkg
      targetFolder: '$(Build.ArtifactStagingDirectory)/nugetArtifact'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/nugetArtifact'
      artifactName: 'SourceGenerator-$(Build.BuildNumber)'

  - task: NuGetCommand@2
    displayName: 'Push Nuget packages'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/nugetArtifact/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '51df80c2-22c2-4f52-ae6e-f59af7e5fa6a'