// PLEASE DONT USE THIS WE PLAN TO REMOVE IT. PLATFORMUI SHOULD KNOW NOTHING OF ACTIONTYPES, USE ACTIONACTIVITY INSTEAD!
/**
 * @deprecated Move to PlatformUI
 */
export enum ActionTypeEnum {
    None = 0,
    CreateJobFrom = 1,
    AssignToRound = 2,
    RelatesToWeighing = 3,
    StartOfCycle = 4,
    EndOfCycle = 5,
    OneOffCharge = 6,
    FastTrackDrop = 7,
    Disposal = 8,
    LandfillTax = 9,
    DemurrageLoading = 10,
    GateJob = 11,
    DemurrageWeighing = 12,
    Rental = 13,
    CallOut = 14,
    SaleJob = 15,
    MaterialSale = 16,
    CreateContainerJobFrom = 17,
    SecondaryProcessing = 18,
    OneOffCost = 19,
    MissedCollectionIncident = 20,
    RouteStatisticViolation = 21,
    CostVATAdjustment = 22,
    TransferOut = 23,
    SecondaryJob = 24,
    Adjustment = 25,
    JobMinimumCharge = 26,
    ManifestProcessing = 27,
    BillFromLiftEvent = 29,
    ChargePerVisit = 28,
    Surcharge = 30,
    ExcludeJobMinCharge = 31,
    AdvanceService = 32,
    DateRelated = 33,
    QuantityBased = 34,
    MinimumBillLevelCharge = 35,
    FailedDirectDebitFee = 36,
    Discount = 37,
    BatchProcessing = 38,
    BandedBased = 39
}
