//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace AMCS.Data.Configuration
{
  public interface IProjectConfiguration
  {
    string ProjectId { get; }

    string ServiceRootName { get; }

  }

#if NETFRAMEWORK 

  public class ProjectConfigurationSection : ConfigurationSection, IProjectConfiguration
  {
    [ConfigurationProperty("projectId", IsRequired = true)]
    public string ProjectId
    {
      get => (string)this["projectId"];
      set => this["projectId"] = value;
    }

    [ConfigurationProperty("serviceRootName", IsRequired = true)]
    public string ServiceRootName
    {
      get => (string)this["serviceRootName"];
      set => this["serviceRootName"] = value;
    }

  }

#else

  public class ProjectConfigurationSection : IProjectConfiguration
  { 
    public string ProjectId { get; }

    public string ServiceRootName { get; }

    public ProjectConfigurationSection (XElement element)
    {
      ProjectId = element?.Attribute("projectId")?.Value != null ? element.Attribute("projectId").Value : default(string);
      ServiceRootName = element?.Attribute("serviceRootName")?.Value != null ? element.Attribute("serviceRootName").Value : default(string);
    }
  }

#endif

}

