export enum AmcsMapProvider {
    GoogleMapsRoadmap = 1,
    GoogleMapsSatellite = 2,
    GoogleMapsTerrain = 3,
    HereMapsStreet = 5,
    HereMapsSatellite = 6,
    HereMapsTerrain = 7,
    Norway = 8,
    TopoGraphic = 9,
    TopoGraphicGrayScale = 10,
    Kartdata = 11,
    NorwayBaseMap = 12,
    NorwayBaseMapGreyScale = 13,
    European = 14,
    Seabed = 15,
    Terrain = 16,
    Nautical = 17,
    Toporaster = 18,
    Fjellskygge = 19,
    Basemap = 20
}
